name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Get dependent binaries from cache
      uses: actions/cache@v1
      with:
        path: ./dependencies
        key: swt.zip-jface-lwjgl-launch4j-tools
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
    - name: Archive windows executable for win32-x64
      uses: actions/upload-artifact@v1
      with:
        name: LDPartEditor-win32-x64
        path: bin
