name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Create directory for dependencies
      shell: bash
      run: |
        mkdir dependecies
    - name: Cache dependent binaries
      uses: actions/cache@v1
      with:
        path: ./dependencies
        key: 4711
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
